### ISSUE TITLE
liveupdate.d.ts file in typings needs to be modified to support better syntax conformation in TypeScript

### ISSUE THREAD

**Issue by rickchoi** [mfpdev/mfp-live-update-cordova-plugin#5]
The current info shows:
**declare module LiveUpdate {**
...
**function getConfiguration (**

but it needs to be:
**declare module LiveUpdateManager {**
...
**function obtainConfiguration (**

to conform with correct syntax support in TypeScript.

**Comment by rajarahul12** [comment]
Fixed in this: https://github.com/mfpdev/mfp-live-update-cordova-plugin/pull/7
